// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE-AjgJxgp3x1X6V6ANeLY0s8KflJLxkI',
    appId: '1:972035622493:android:a6367a83b6102c03d62fb4',
    messagingSenderId: '972035622493',
    projectId: 'pathfinder-bae0f',
    databaseURL: 'https://pathfinder-bae0f-default-rtdb.firebaseio.com',
    storageBucket: 'pathfinder-bae0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyByPGB-9mJ4bN8Yurdy9oQ5klrMAFb9c',
    appId: '1:972035622493:ios:652c853d72f48a14d62fb4',
    messagingSenderId: '972035622493',
    projectId: 'pathfinder-bae0f',
    databaseURL: 'https://pathfinder-bae0f-default-rtdb.firebaseio.com',
    storageBucket: 'pathfinder-bae0f.appspot.com',
    iosBundleId: 'com.example.pathFinder',
  );

}